

-- ユーザー テーブル
CREATE TABLE USER (
	USER_ID	BIGINT NOT NULL IDENTITY ,
	USER_NAME	VARCHAR(65536) NOT NULL UNIQUE ,
	USER_PASSWORD	VARCHAR(65536) NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) ,
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	PRIMARY KEY( USER_ID )
);


-- ユーザープロパティ テーブル
CREATE TABLE USER_PROPERTIES (
	USER_PROPERTY_ID BIGINT NOT NULL IDENTITY ,
	USER_ID	BIGINT NOT NULL ,
	USER_PROPERTY_KEY	VARCHAR(65536) NOT NULL ,
	USER_PROPERTY_VALUE	VARCHAR(65536) NOT NULL ,
	USER_PROPERTY_EXPLAIN	VARCHAR(65536) NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE ( USER_ID , USER_PROPERTY_KEY ) ,
	PRIMARY KEY( USER_PROPERTY_ID , USER_ID )
);



-- ユーザーグループ テーブル
CREATE TABLE USER_GROUP (
	USER_GROUP_ID	BIGINT NOT NULL IDENTITY ,
	USER_GROUP_NAME	VARCHAR(65536) NOT NULL UNIQUE ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) ,
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	PRIMARY KEY( USER_GROUP_ID )
);


-- ユーザーグループプロパティ テーブル
CREATE TABLE USER_GROUP_PROPERTIES (
	USER_GROUP_PROPERTY_ID BIGINT NOT NULL IDENTITY ,
	USER_GROUP_ID	BIGINT NOT NULL ,
	USER_GROUP_PROPERTY_KEY	VARCHAR(65536) NOT NULL ,
	USER_GROUP_PROPERTY_VALUE	VARCHAR(65536) NOT NULL ,
	USER_GROUP_PROPERTY_EXPLAIN	VARCHAR(65536) NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE ( USER_GROUP_ID , USER_GROUP_PROPERTY_KEY ) ,
	PRIMARY KEY( USER_GROUP_PROPERTY_ID , USER_GROUP_ID )
);




-- ユーザーグループマッピング テーブル
CREATE TABLE USER_GROUP_MAPPING (
	USER_GROUP_MAPPING_ID BIGINT NOT NULL IDENTITY ,
	USER_ID	BIGINT NOT NULL ,
	USER_GROUP_ID	BIGINT NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) ,
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	PRIMARY KEY( USER_ID, USER_GROUP_ID )
);



-- ユーザーグループ権限 テーブル
-- 		DNS_INFO_MASK_VALUE 列
-- 			000	: DNS情報の参照権限なし
--			001 : DNS情報(自身)の読み取り可能
-- 			002 : DNS情報(グループ内)の読み取り可能
-- 			003 : DNS情報(システム全体)の読み取り可能
--			010 : DNS情報(自身)の更新可能
-- 			020 : DNS情報(グループ内)の更新可能
-- 			030 : DNS情報(システム全体)の更新可能
-- 			100 : DNS情報(自身)の作成/削除可能
-- 			200 : DNS情報(グループ内)の作成/削除可能
-- 			300 : DNS情報(システム全体)の作成/削除可能

-- 		USER_INFO_MASK_VALUE 列
--  		000	: ユーザー情報の参照権限なし
-- 			001 : ユーザー情報(自身)の読み取り可能
-- 			002 : ユーザー情報(グループ内)の読み取り可能
-- 			003 : ユーザー情報(システム全体)の読み取り可能
-- 			010 : ユーザー情報(自身)の更新可能
-- 			020 : ユーザー情報(グループ内)の更新可能
-- 			030 : ユーザー情報(システム全体)の更新可能
-- 			100 : ユーザー情報(自身)の作成/削除可能
-- 			200 : ユーザー情報(グループ内)の作成/削除可能
-- 			300 : ユーザー情報(システム全体)の作成/削除可能

-- 		SYSTEM_INFO_MASK_VALUE 列
--  		000	: システム情報の参照権限なし
-- 			001 : システム情報(自身)の読み取り可能
-- 			002 : システム情報(グループ内)の読み取り可能
-- 			003 : システム情報(システム全体)の読み取り可能
-- 			010 : システム情報(自身)の更新可能
-- 			020 : システム情報(グループ内)の更新可能
-- 			030 : システム情報(システム全体)の更新可能
-- 			100 : システム情報(自身)の作成/削除可能
-- 			200 : システム情報(グループ内)の作成/削除可能
-- 			300 : システム情報(システム全体)の作成/削除可能
CREATE TABLE USER_GROUP_PRIVILEGE (
	USER_GROUP_PRIVILEGE_ID	BIGINT NOT NULL IDENTITY ,
	USER_GROUP_ID	BIGINT NOT NULL UNIQUE,
	DNS_INFO_MASK_VALUE	BIGINT NOT NULL ,
	USER_INFO_MASK_VALUE	BIGINT NOT NULL ,
	SYSTEM_INFO_MASK_VALUE	BIGINT NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) ,
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	PRIMARY KEY( USER_GROUP_PRIVILEGE_ID, USER_GROUP_ID )
);


--  DNSサービスインスタンス テーブル
--		DNS_RESOLVER_INSTANCE_ID 列 : このDNSサービスインスタンスが使用するDNSリゾルバインスタンスのIDを指定する
CREATE TABLE DNS_SERVICE_INSTANCE (
	DNS_SERVICE_INSTANCE_ID	BIGINT NOT NULL IDENTITY ,
	USER_ID	BIGINT NOT NULL ,
	DNS_SERVICE_INSTANCE_NAME	VARCHAR(65536) NOT NULL ,
	DNS_SERVICE_INSTANCE_EXPLAIN	VARCHAR(65536) NOT NULL ,
	DNS_SERVICE_TYPE_CODE 	BIGINT NOT NULL ,
	DNS_RESOLVER_INSTANCE_ID 	BIGINT NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE (USER_ID, DNS_SERVICE_INSTANCE_NAME) ,
	PRIMARY KEY( DNS_SERVICE_INSTANCE_ID, USER_ID )
);


--  DNSサービスインスタンスプロパティ テーブル
--		DNS_SERVICE_INSTANCE_ID 列 : このDNSサービスインスタンスプロパティが所属するDNSサービスインスタンスのIDを指定する.
CREATE TABLE DNS_SERVICE_INSTANCE_PROPERTIES (
	DNS_SERVICE_INSTANCE_PROPERTY_ID	BIGINT NOT NULL IDENTITY ,
	DNS_SERVICE_INSTANCE_ID	BIGINT NOT NULL ,
	DNS_SERVICE_INSTANCE_PROPERTY_KEY	VARCHAR(65536) NOT NULL ,
	DNS_SERVICE_INSTANCE_PROPERTY_VALUE	VARCHAR(65536) NOT NULL ,
	DNS_SERVICE_INSTANCE_PROPERTY_EXPLAIN	VARCHAR(65536) NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE (DNS_SERVICE_INSTANCE_ID, DNS_SERVICE_INSTANCE_PROPERTY_KEY) ,
	PRIMARY KEY( DNS_SERVICE_INSTANCE_PROPERTY_ID, DNS_SERVICE_INSTANCE_ID )
);


--  DNSサービスのエンドポイントインスタンス テーブル
--		DNS_SERVICE_INSTANCE_ID 列 : このサービスエンドポイントが所属するDNSサービスインスタンスのIDを指定する.
--
-- 		DNS_SERVICE_ENDPOINT_TYPE_CODE 列 : このサービスエンドポイントの種類を以下の定数値で指定する.		
--				1101 : UDP
--				1201 : TCP
--				1501 : DoH
--				1601 : DoT

CREATE TABLE DNS_SERVICE_ENDPOINT_INSTANCE (
	DNS_SERVICE_ENDPOINT_INSTANCE_ID	BIGINT NOT NULL IDENTITY ,
	DNS_SERVICE_INSTANCE_ID	BIGINT NOT NULL ,
	DNS_SERVICE_ENDPOINT_INSTANCE_NAME	VARCHAR(65536) NOT NULL ,
	DNS_SERVICE_ENDPOINT_INSTANCE_EXPLAIN	VARCHAR(65536) NOT NULL ,
	DNS_SERVICE_ENDPOINT_TYPE_CODE 	BIGINT NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE (DNS_SERVICE_INSTANCE_ID, DNS_SERVICE_ENDPOINT_INSTANCE_NAME) ,
	PRIMARY KEY( DNS_SERVICE_ENDPOINT_INSTANCE_ID, DNS_SERVICE_INSTANCE_ID )
);


--  DNSサービスのエンドポイントインスタンスプロパティ テーブル
--		DNS_SERVICE_ENDPOINT_INSTANCE_ID 列 : このサービスエンドポイントのプロパティ情報が所属するDNSサービスエンドポイントインスタンスのIDを指定する.
CREATE TABLE DNS_SERVICE_ENDPOINT_INSTANCE_PROPERTIES (
	DNS_SERVICE_ENDPOINT_INSTANCE_PROPERTY_ID	BIGINT NOT NULL IDENTITY ,
	DNS_SERVICE_ENDPOINT_INSTANCE_ID	BIGINT NOT NULL ,
	DNS_SERVICE_ENDPOINT_INSTANCE_PROPERTY_KEY	VARCHAR(65536) NOT NULL ,
	DNS_SERVICE_ENDPOINT_INSTANCE_PROPERTY_VALUE	VARCHAR(65536) NOT NULL ,
	DNS_SERVICE_ENDPOINT_INSTANCE_PROPERTY_EXPLAIN	VARCHAR(65536) NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE (DNS_SERVICE_ENDPOINT_INSTANCE_ID, DNS_SERVICE_ENDPOINT_INSTANCE_PROPERTY_KEY) ,
	PRIMARY KEY( DNS_SERVICE_ENDPOINT_INSTANCE_PROPERTY_ID, DNS_SERVICE_ENDPOINT_INSTANCE_ID )
);



--  DNSリゾルバインスタンス テーブル
-- 		DNS_RESOLVER_TYPE	
--			特殊リゾルバ
--				000 : NULLリゾルバ(何も返さない)
-- 
--			集約リゾルバ
-- 				101 : 先順位優先レコード発見型集約リゾルバ(先順位優先(応答内容確保型) : 該当するDNSレコードが見つかるまで所属リゾルバを先順位から順に問い合わせる)
-- 				102 : 先順位優先無レコード型集約リゾルバ(先順位優先 : 所属リゾルバを先順位から順番に問い合わせる.該当するDNSレコードが見つからなくても応答する)
-- 				111 : ラウンドロビン型分散問い合わせ集約リゾルバ(分散問い合わせ(ラウンドロビン) : 所属リゾルバをラウンドロビンで分散問い合わせ )
-- 				112 : ランダム型分散問い合わせ集約リゾルバ(分散問い合わせ(ランダム) : 所属リゾルバをランダムに分散問い合わせ )
-- 				121 : 多数決型同時問い合わせリゾルバ(多数決型 : 所属下位リゾルバが3つ以上ある場合に多数決で決する)
-- 				122 : 全会一致型同時問い合わせリゾルバ(全会一致型 : 所属下位リゾルバの問い合わせ結果が全会一致する場合にのみ正常応答する)
-- 
--			外部問い合わせリゾルバ
-- 				201 : UDP(DNS)問い合わせ
-- 				202 : TCP(DNS)問い合わせ
--	 			203 : DNSSec問い合わせ
-- 				204 : DoT(DNS over TLS)問い合わせ
--				205	: DoH(DNS over HTTPS)問い合わせ
-- 
--			内部応答リゾルバ
--				301 : 外部ゾーンファイル参照型内部応答リゾルバ (システムが外部ゾーンファイルを参照して応答する)
--				302 : 内蔵DB内ゾーンファイル参照型内部応答リゾルバ (システムが内蔵DBの中にあるゾーンファイルを参照して応答する)
--				311 : 外部HOSTSファイル参照型内部応答リゾルバ (システムが外部HOSTSファイルを参照して応答する)
--				312 : 内蔵DB内HOSTSファイル参照型内部応答リゾルバ (システムが内蔵DBの中にあるHOSTSファイルを参照して応答する)
-- 
--			キャッシュリゾルバ
--				801 : 所属リゾルバキャッシュ(所属下位リゾルバのクエリ結果をキャッシュ)			
--				802 : 所属ユーザーキャッシュ(同一ユーザーに所属するDNSリゾルバのクエリ結果をキャッシュ)		
--				802 : 所属ユーザーグループキャッシュ(同一ユーザーグループに所属するDNSリゾルバのクエリ結果をキャッシュ)		
--				803 : システム全体キャッシュ(システム全体のDNSリゾルバのクエリ結果をキャッシュ)		
CREATE TABLE DNS_RESOLVER_INSTANCE (
	DNS_RESOLVER_INSTANCE_ID	BIGINT NOT NULL IDENTITY ,
	USER_ID	BIGINT NOT NULL ,
	DNS_RESOLVER_INSTANCE_NAME	VARCHAR(65536) NOT NULL ,
	DNS_RESOLVER_INSTANCE_EXPLAIN	VARCHAR(65536) NOT NULL ,
	DNS_RESOLVER_TYPE_CODE	BIGINT NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE ( USER_ID , DNS_RESOLVER_INSTANCE_NAME ) ,
	PRIMARY KEY( DNS_RESOLVER_INSTANCE_ID )
);



-- DNSリゾルバインスタンスのプロパティ テーブル 
CREATE TABLE DNS_RESOLVER_INSTANCE_PROPERTIES (
	DNS_RESOLVER_INSTANCE_PROPERTY_ID BIGINT NOT NULL IDENTITY ,
	DNS_RESOLVER_INSTANCE_ID	BIGINT NOT NULL ,
	DNS_RESOLVER_INSTANCE_PROPERTY_KEY	VARCHAR(65536) NOT NULL ,
	DNS_RESOLVER_INSTANCE_PROPERTY_VALUE	VARCHAR(65536) NOT NULL ,
	DNS_RESOLVER_INSTANCE_PROPERTY_EXPLAIN	VARCHAR(65536) NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE ( DNS_RESOLVER_INSTANCE_ID , DNS_RESOLVER_INSTANCE_PROPERTY_KEY ) ,
	PRIMARY KEY( DNS_RESOLVER_INSTANCE_PROPERTY_ID, DNS_RESOLVER_INSTANCE_ID )
);


-- DNSリゾルバタイプ テーブル 
-- 		DNS_RESOLVER_TYPE_CODE	
--			特殊リゾルバ
--				000 : NULLリゾルバ(何も返さない)
-- 
--			集約リゾルバ
-- 				101 : 先順位優先レコード発見型集約リゾルバ(先順位優先(応答内容確保型) : 該当するDNSレコードが見つかるまで所属リゾルバを先順位から順に問い合わせる)
-- 				102 : 先順位優先無レコード型集約リゾルバ(先順位優先 : 所属リゾルバを先順位から順番に問い合わせる.該当するDNSレコードが見つからなくても応答する)
-- 				111 : ラウンドロビン型分散問い合わせ集約リゾルバ(分散問い合わせ(ラウンドロビン) : 所属リゾルバをラウンドロビンで分散問い合わせ )
-- 				112 : ランダム型分散問い合わせ集約リゾルバ(分散問い合わせ(ランダム) : 所属リゾルバをランダムに分散問い合わせ )
-- 				121 : 多数決型同時問い合わせリゾルバ(多数決型 : 所属下位リゾルバが3つ以上ある場合に多数決で決する)
-- 				122 : 全会一致型同時問い合わせリゾルバ(全会一致型 : 所属下位リゾルバの問い合わせ結果が全会一致する場合にのみ正常応答する)
-- 
--			外部問い合わせリゾルバ
-- 				201 : UDP(DNS)問い合わせ
-- 				202 : TCP(DNS)問い合わせ
--	 			203 : DNSSec問い合わせ
-- 				204 : DoT(DNS over TLS)問い合わせ
--				205	: DoH(DNS over HTTPS)問い合わせ
-- 
--			内部応答リゾルバ
--				301 : 外部ゾーンファイル参照型内部応答リゾルバ (システムが外部ゾーンファイルを参照して応答する)
--				302 : 内蔵DB内ゾーンファイル参照型内部応答リゾルバ (システムが内蔵DBの中にあるゾーンファイルを参照して応答する)
--				311 : 外部HOSTSファイル参照型内部応答リゾルバ (システムが外部HOSTSファイルを参照して応答する)
--				312 : 内蔵DB内HOSTSファイル参照型内部応答リゾルバ (システムが内蔵DBの中にあるHOSTSファイルを参照して応答する)
-- 
--			キャッシュリゾルバ
--				801 : 所属リゾルバキャッシュ(所属下位リゾルバのクエリ結果をキャッシュ)			
--				802 : 所属ユーザーキャッシュ(同一ユーザーに所属するDNSリゾルバのクエリ結果をキャッシュ)		
--				802 : 所属ユーザーグループキャッシュ(同一ユーザーグループに所属するDNSリゾルバのクエリ結果をキャッシュ)		
--				803 : システム全体キャッシュ(システム全体のDNSリゾルバのクエリ結果をキャッシュ)		
CREATE TABLE DNS_RESOLVER_TYPE (
	DNS_RESOLVER_TYPE_ID BIGINT NOT NULL IDENTITY ,
	DNS_RESOLVER_TYPE_CODE BIGINT NOT NULL UNIQUE ,
	DNS_RESOLVER_TYPE_NAME VARCHAR(65536) NOT NULL UNIQUE ,
	DNS_RESOLVER_TYPE_EXPLAIN VARCHAR(65536) NOT NULL ,
	DNS_RESOLVER_CLASS_NAME VARCHAR(65536)  ,
	DNS_RESOLVER_CLASS_LOADER_NAME VARCHAR(65536)  ,
	DNS_RESOLVER_OPTION_1 VARCHAR(65536)  ,
	DNS_RESOLVER_OPTION_2 VARCHAR(65536)  ,
	DNS_RESOLVER_OPTION_3 VARCHAR(65536)  ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	PRIMARY KEY( DNS_RESOLVER_TYPE_ID )
);



-- DNSリゾルバタイプのプロパティ テーブル 
CREATE TABLE DNS_RESOLVER_TYPE_PROPERTIES (
	DNS_RESOLVER_TYPE_PROPERTY_ID BIGINT NOT NULL IDENTITY ,
	DNS_RESOLVER_TYPE_ID	BIGINT NOT NULL ,
	DNS_RESOLVER_TYPE_PROPERTY_KEY	VARCHAR(65536) NOT NULL ,
	DNS_RESOLVER_TYPE_PROPERTY_VALUE	VARCHAR(65536) NOT NULL ,
	DNS_RESOLVER_TYPE_PROPERTY_EXPLAIN	VARCHAR(65536) NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE ( DNS_RESOLVER_TYPE_ID , DNS_RESOLVER_TYPE_PROPERTY_KEY ) ,
	PRIMARY KEY( DNS_RESOLVER_TYPE_PROPERTY_ID, DNS_RESOLVER_TYPE_ID )
);




-- システムプロパティ テーブル
CREATE TABLE SYSTEM_PROPERTIES (
	SYSTEM_PROPERTY_ID BIGINT NOT NULL IDENTITY ,
	SYSTEM_PROPERTY_KEY	VARCHAR(65536) NOT NULL ,
	SYSTEM_PROPERTY_VALUE	VARCHAR(65536) NOT NULL ,
	SYSTEM_PROPERTY_EXPLAIN	VARCHAR(65536) NOT NULL ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE ( SYSTEM_PROPERTY_KEY ) ,
	PRIMARY KEY( SYSTEM_PROPERTY_ID )
);


-- 共通システムログ
CREATE TABLE COMMON_SYSTEM_LOG (
	COMMON_SYSTEM_LOG_ID BIGINT NOT NULL IDENTITY ,
	COMMON_SYSTEM_LOG_TAG	VARCHAR(65536) NOT NULL ,
	COMMON_SYSTEM_LOG_RECORD	VARCHAR(65536) NOT NULL ,
	COMMON_SYSTEM_LOG_OCCUR_DATE	VARCHAR(65536) NOT NULL ,
	COMMON_SYSTEM_LOG_OPTION1	VARCHAR(65536) ,
	COMMON_SYSTEM_LOG_OPTION2	VARCHAR(65536) ,
	COMMON_SYSTEM_LOG_OPTION3	VARCHAR(65536) ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	PRIMARY KEY( COMMON_SYSTEM_LOG_ID )
);


-- 共通システムログプロパティ
CREATE TABLE COMMON_SYSTEM_LOG_PROPERTIES (
	COMMON_SYSTEM_LOG_PROPERTY_ID BIGINT NOT NULL IDENTITY ,
	COMMON_SYSTEM_LOG_ID BIGINT ,
	COMMON_SYSTEM_LOG_PROPERTY_KEY	VARCHAR(65536) NOT NULL,
	COMMON_SYSTEM_LOG_PROPERTY_VALUE	VARCHAR(65536) NOT NULL,
	COMMON_SYSTEM_LOG_PROPERTY_OPTION1	VARCHAR(65536) ,
	COMMON_SYSTEM_LOG_PROPERTY_OPTION2	VARCHAR(65536) ,
	COMMON_SYSTEM_LOG_PROPERTY_OPTION3	VARCHAR(65536) ,
	RECORD_STATUS BIGINT NOT NULL ,
	MEMO	VARCHAR(65536) , 
	CREATE_DATE VARCHAR(65536) ,
	UPDATE_DATE VARCHAR(65536) ,
	UNIQUE ( COMMON_SYSTEM_LOG_ID, COMMON_SYSTEM_LOG_PROPERTY_KEY ) ,
	PRIMARY KEY( COMMON_SYSTEM_LOG_PROPERTY_ID )
);



