spring.datasource.sqlScriptEncoding=UTF-8
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=jdbc:hsqldb:file:./LoulanDNS/db/HSQLDB/LoulanDNS/LoulanDNS
spring.datasource.username=loulan
spring.datasource.password=loulan

jpa.hibernate.ddl-auto=validate

logging.level.sql=debug




